### ISSUE TITLE
Store historical data to be able to get some stats

### ISSUE THREAD

**Issue by shordeaux** [anishathalye/offix#12]
It would be nice to store sessions (user_id, start_at, end_at)

**Comment by anishathalye** [comment]
I did this in a related [project](https://github.com/anishathalye/mas330/blob/master/app.js).

Not sure if we want to do it for [my use case](https://www.anishathalye.com/2016/06/03/whos-in-the-office/) (people might be creeped out by it).

Though I'm not opposed to adding the feature, as long as there's a switch to disable it.

**Comment by anishathalye** [comment]
Closing due to age
