### ISSUE TITLE
I want some helps about set up hubot links

### ISSUE THREAD

**Issue by baolintian** [anishathalye/offix#17]
Recently I want to reproduce this project but I encountered some problems, thank for guiding me to step further. The questions are:
1. How hubot get the web user login data? I don't know how to configure the url. Through file or just cmd? Please provide an example maybe better.
2. How can we configure `HUBOT_OFFIX_BASEURL`, `HUBOT_OFFIX_KEY` these variables? In command line or in file?
my start cmd is `HUBOT_SLACK_TOKEN=xoxb-xx-xx HUBOT_OFFIX_BASEURL="http://localhost:3000/" HUBOT_OFFIX_KEY=14efe32635798c9ca3eb7ce596b9c0e329a71b7081c801c634efebf69935c668 HUBOT_OFFIX_LIMIT=2 ./bin/hubot --adapter slack`
Thanks a lot for your kind help~

**Comment by anishathalye** [comment]
1. You configure the secret in `config.js` (see [sample](https://github.com/anishathalye/offix/blob/master/offix-web/config.sample.js#L17)).
2. Either environment variable or in the chat. See docs for [hubot-conf](https://www.npmjs.com/package/hubot-conf). That start command looks fine.

**Comment by baolintian** [comment]
Wow,  I have successfully reproduced this project with your generous help. The above command line is fine. I will recommend this interesting project for my classmates. Maybe later I will write an article about `offix` to  propagandize it. Anyway thank for your help~:smile:

**Comment by baolintian** [comment]
I wrote a setup article about this project. Maybe it is useful for someone who understands Chinese [link](https://zhuanlan.zhihu.com/p/202903802).

**Comment by anishathalye** [comment]
Great! Thanks for sharing the link!
